version: "3"
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  client:
    volumes:
      - ./client:/workspace
      - ./common:/workspace/common
      - ./data:/workspace/data

    entrypoint: /bin/sh -c "while sleep 1000; do :; done"

  joiner:
    volumes:
      - ./joiner:/workspace
      - ./common:/workspace/common

    entrypoint: /bin/sh -c "while sleep 1000; do :; done"

  # dropper:
  #   volumes:
  #     - ./dropper:/workspace
  #     - ./common:/workspace/common

  #   entrypoint: /bin/sh -c "while sleep 1000; do :; done"

  # likes_filter:
  #   volumes:
  #     - ./likes_filter:/workspace
  #     - ./common:/workspace/common

  #   entrypoint: /bin/sh -c "while sleep 1000; do :; done"

  # tag_unique:
  #   volumes:
  #     - ./tag_unique:/workspace
  #     - ./common:/workspace/common
  #   entrypoint: /bin/sh -c "while sleep 1000; do :; done"

  # trending_router:
  #   volumes:
  #     - ./trending_router:/workspace
  #     - ./common:/workspace/common

  #   entrypoint: /bin/sh -c "while sleep 1000; do :; done"

  # thumbnail_instance:
  #   volumes:
  #     - ./thumbnail_instance:/workspace
  #     - ./common:/workspace/common

  #   entrypoint: /bin/sh -c "while sleep 1000; do :; done"

  # trending_top:
  #   volumes:
  #     - ./trending_top:/workspace
  #     - ./common:/workspace/common

  #   entrypoint: /bin/sh -c "while sleep 1000; do :; done"

  # downloader:
  #   volumes:
  #     - ./downloader:/workspace
  #     - ./common:/workspace/common

  #   entrypoint: /bin/sh -c "while sleep 1000; do :; done"
