REPLICAS_CLIENT=6
REPLICAS_JOINER=2
REPLICAS_DROPPER=2
REPLICAS_TRENDING=2
REPLICAS_THUMBNAIL=2
REPLICAS_LIKES_FILTER=1
REPLICAS_WATCHERS=0
TRENDING_ROUTER_ENABLED=1
THUMBNAIL_ROUTER_ENABLED=1
DOWNLOADER_ENABLED=1
TAG_UNIQUE_ENABLED=1
TRENDING_TOP_ENABLED=1
ACCEPTOR_ENABLED=1

bash ./dfile_gen.sh $REPLICAS_CLIENT $REPLICAS_JOINER $REPLICAS_DROPPER $REPLICAS_TRENDING $REPLICAS_THUMBNAIL $REPLICAS_LIKES_FILTER $REPLICAS_WATCHERS $TRENDING_ROUTER_ENABLED $THUMBNAIL_ROUTER_ENABLED $DOWNLOADER_ENABLED $TAG_UNIQUE_ENABLED $TRENDING_TOP_ENABLED $ACCEPTOR_ENABLED