version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    build: rabbitmq/.
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none
  client:
    container_name: client
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    entrypoint: python3 main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBIT_SERVER_ADDRESS=rabbitmq
      - LOGGING_LEVEL=INFO
      - FILE_READER_LINES=20
    volumes:
      - ./data:/workspace/data
  # joiner:
  #   container_name: joiner
  #   build:
  #     context: ./
  #     dockerfile: ./joiner/Dockerfile
  #   entrypoint: python3 main.py
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - RABBIT_SERVER_ADDRESS=rabbitmq
  #     - LOGGING_LEVEL=INFO
  dropper:
    deploy:
      replicas: 5
    build:
      context: ./
      dockerfile: ./dropper/Dockerfile
    entrypoint: python3 main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBIT_SERVER_ADDRESS=rabbitmq
      - LOGGING_LEVEL=INFO
