version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    build: rabbitmq/.
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 5
  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
