#!/bin/bash

KILLEABLES=('^/thumbnail_router$' '^/thumbnail_[[:digit:]]+$' '^/joiner_[[:digit:]]+$')
echo $KILLEABLES
KILLEABLES_SIZE=${#KILLEABLES[@]}
echo $KILLEABLES_SIZE
KILLEABLES_INDEX=$(($RANDOM % $KILLEABLES_SIZE))
echo $KILLEABLES_INDEX
KILL_SELECTED=${KILLEABLES[$KILLEABLES_INDEX]}
echo $KILL_SELECTED

CONTAINERS=($(docker ps -aq --filter name="$KILL_SELECTED"))
echo $CONTAINERS
CONTAINER_SIZE=${#CONTAINERS[@]}
echo $CONTAINER_SIZE
CONTAINER_INDEX=$(($RANDOM % $CONTAINER_SIZE))
echo $CONTAINER_INDEX
CONTAINER_SELECTED=${CONTAINERS[$CONTAINER_INDEX]}

echo "Killing container $CONTAINER_SELECTED"