
DEFAULT_BULLY_CHECK_RETRIES = 3
DEFAULT_BULLY_CHECK_FRECUENCY = 2

DEFAULT_BULLY_LEADER_TIMEOUT = 5 #In seconds
DEFAULT_BULLY_SLAVES_TIMEOUT = 5 #In seconds
DEFAULT_BULLY_ELECTION_TIMEOUT = 5 #In seconds
DEFAULT_BULLY_LISTENING_TIMEOUT = 1.0 #In seconds

DEFAULT_CONFIG = {
    "loggin_level": "INFO",
    "bully_check_retries": DEFAULT_BULLY_CHECK_RETRIES,
    "bully_check_frecuency": DEFAULT_BULLY_CHECK_FRECUENCY,
    "bully_leader_timeout": DEFAULT_BULLY_LEADER_TIMEOUT,
    "bully_slave_timeout": DEFAULT_BULLY_SLAVES_TIMEOUT,
    "bully_election_timeout": DEFAULT_BULLY_ELECTION_TIMEOUT,
    "bully_listening_timeout": DEFAULT_BULLY_LISTENING_TIMEOUT 
}